# -*- coding: utf-8 -*-
"""acdt_g31

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5fm0D95_3CLMpKv3LVVCJCWz4Vwmcv_
"""

import streamlit as st
import pandas as pd

DATA_FILE = "ACDT_final_dataset.csv"

@st.cache_data
def read_and_clean(path: str, debug=False):
    raw = None
    last_err = None
    for enc in ('utf-8-sig', 'cp949'):
        try:
            raw = pd.read_csv(path, encoding=enc, header=None, engine='python')
            break
        except Exception as e:
            last_err = e
    if raw is None:
        raise RuntimeError(f"CSV reading fail: {last_err}")

    if debug:
        st.subheader("Debug Mode")
        st.write(f"shape: {raw.shape}")
        st.write("row 0 (year):", raw.iloc[0, :].astype(str).tolist()[:30])
        st.write("row 1 (indicator names):", raw.iloc[1, :].astype(str).tolist()[:30])
        st.dataframe(raw.head(6))
        st.info("Stopped application after listing data")
        st.stop()

    # 연도 및 지표 추출은 이후에...

    return raw  # 혹은 후처리된 dataframe 반환

# UI에서 디버그 토글 구현 부분 예시

st.title("ACDT G31 분석")

debug_mode = st.sidebar.checkbox("Debug", False)

df_raw = read_and_clean(DATA_FILE, debug=debug_mode)

if debug_mode:
    st.warning("Stopped by debug mode")
    st.stop()

# 그 외 데이터 처리, 분석, 시각화 로직 진행

# report_app.py
import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="ACDT Group 31 — GERD → GDP Report",
    layout="wide",
    page_icon="📈",
)

# ──────────────────────────────────────────────────────────────
# 헤더
# ──────────────────────────────────────────────────────────────
st.title("📈 GERD → GDP Analysis — Report View (ACDT Group 31)")
st.caption("Linear Regression • Multiple Linear Regression (Confounder / Mediator / Moderator) • Key Implications")
st.markdown("---")

# ──────────────────────────────────────────────────────────────
# 1) Linear Regression (단변량)
# ──────────────────────────────────────────────────────────────
st.header("1) Linear Regression (단변량)")

colL, colR = st.columns(2)

with colL:
    st.subheader("GERD (2020) → GDP (2022)")
    lin_2022 = pd.DataFrame(
        [
            ["Slope (β₁)", "0.6330"],
            ["Intercept (β₀)", "0.7860"],
            ["R (corr.)", "0.7754"],
            ["p-value", "0.0000"],
            ["Std. Error", "0.1099"],
        ],
        columns=["Metric", "Value"],
    )
    st.dataframe(lin_2022, hide_index=True, use_container_width=True)
    st.markdown(
        "로그-로그 해석: **GERD 1% 증가 → GDP 약 0.63% 증가 경향** (통계적으로 매우 유의)."
    )

with colR:
    st.subheader("GERD (2020) → GDP (2023)")
    lin_2023 = pd.DataFrame(
        [
            ["Slope (β₁)", "0.6324"],
            ["Intercept (β₀)", "0.8005"],
            ["R (corr.)", "0.7746"],
            ["p-value", "0.0000"],
            ["Std. Error", "0.1101"],
        ],
        columns=["Metric", "Value"],
    )
    st.dataframe(lin_2023, hide_index=True, use_container_width=True)
    st.markdown("두 해 모두 효과 크기와 유의성이 거의 동일함.")

st.markdown("---")

# ──────────────────────────────────────────────────────────────
# 2) Variables from the dataset
# ──────────────────────────────────────────────────────────────
st.header("2) Variables from the Dataset")

c1, c2, c3 = st.columns(3)

with c1:
    st.subheader("🧭 Moderators")
    df_mod = pd.DataFrame(
        [
            ["Government incentives", "Government-financed BERD (%)"],
            ["Venture funding", "Business-financed BERD (%)"],
            ["Labor market", "R&D Personnel per 1000 employees"],
        ],
        columns=["Concept", "Dataset Variable"],
    )
    st.dataframe(df_mod, hide_index=True, use_container_width=True)

with c2:
    st.subheader("🧪 Mediators")
    df_med = pd.DataFrame(
        [
            ["Innovation output", "Resident / Non-resident Patents"],
            ["R&D human capital", "R&D Researchers per million"],
            ["Technological exports", "High-tech Export Share"],
            ["Productivity of firms", "Business R&D Personnel (FTE)"],
        ],
        columns=["Concept", "Dataset Variable"],
    )
    st.dataframe(df_med, hide_index=True, use_container_width=True)

with c3:
    st.subheader("⚠️ Confounders")
    df_conf = pd.DataFrame(
        [
            ["Fiscal capacity", "GDP per capita"],
            ["Population size", "Population / Labor size"],
        ],
        columns=["Concept", "Dataset Variable"],
    )
    st.dataframe(df_conf, hide_index=True, use_container_width=True)

st.markdown("---")

# ──────────────────────────────────────────────────────────────
# 3) Multiple Linear Regression (Model 1–4)
# ──────────────────────────────────────────────────────────────
st.header("3) Multiple Linear Regression (Model 1–4)")

st.subheader("📋 Model Comparison (요약표)")
summary_rows = [
    ["Model 1", "Log_Real_GDP ~ Log_GERD", "0.494", "0.5334", "0.001", "직접효과(단변량)"],
    ["Model 2", "Log_Real_GDP ~ Log_GERD + GDP_per_Capita", "0.476", "0.5044", "0.003", "교란통제(1)"],
    ["Model 3", "Log_Real_GDP ~ Log_GERD + GDP_pc + Mediators", "0.700", "0.3797", "0.020", "매개변수 포함"],
    ["Model 4", "Log_Real_GDP ~ Log_GERD * GovFinanced_BERD(%) + ...", "0.775", "1.0697", "<0.001", "조절(상호작용)"],
]
df_models = pd.DataFrame(
    summary_rows, columns=["Model", "Formula (요약)", "Adj. R²", "β(Log_GERD)", "p(Log_GERD)", "Note"]
)
st.dataframe(df_models, hide_index=True, use_container_width=True)

with st.expander("📘 Full outputs (요약 발췌)"):
    st.code(
        """Model 1 — Adj. R²: 0.494 | Log_GERD: 0.5334 (p=0.001)
Model 2 — Adj. R²: 0.476 | Log_GERD: 0.5044 (p=0.003) | GDP_per_Capita: p=0.491
Model 3 — Adj. R²: 0.700 | Log_GERD: 0.3797 (p=0.020) | Resident Patents: p≈0.053
Model 4 — Adj. R²: 0.775 | ln_GERD×GovFinanced_BERD(%): −0.0895 (p=0.001)
* Condition number large → 다중공선성 가능성 유의"""
    )

# ──────────────────────────────────────────────────────────────
# 4) Interpretation & Implications
# ──────────────────────────────────────────────────────────────
st.header("4) Interpretation & Implications")

bullets = """
- **일관된 양(+) 효과**: 모든 모형에서 `Log(GERD)` ↗ `Log(Real GDP)` (*p* < .05)
- **매개 가능성**: Resident Patents가 **부분 매개** 신호 (*p* ≈ .053)
- **조절 효과**: Government-financed BERD(%)가 높을수록 GERD→GDP 효과 **약화** (상호작용 *p* = .001)
- **설명력 향상**: Adjusted R² `0.494 → 0.775` (모형 확장에 따라 증가)
- **해석 팁**: 로그–로그 모형에서 β는 탄력성(elasticity): GERD 1% 증가 시 GDP가 평균적으로 β% 변동
"""
st.markdown(bullets)

st.markdown("---")

# ──────────────────────────────────────────────────────────────
# 5) Summary Narrative (그대로 붙여넣은 본문)
# ──────────────────────────────────────────────────────────────
st.header("Appendix — Full Narrative (과제 제출용 본문)")
long_text = """
Summary
This analysis was conducted to examine the causal impact of Gross Domestic Expenditure on R&D (GERD) on Real GDP.
Four regression models were sequentially estimated, gradually adding confounding, mediating, and moderating variables to identify the underlying causal structure.
The changes in regression coefficients, statistical significance, and explanatory power (Adjusted R²) were analyzed to interpret the causal relationships.

Model 1: Simple Linear Regression (Log_Real_GDP ~ Log_GERD)
Model 1 estimates the simple linear relationship between Log(GERD) and Log(Real GDP).
The regression coefficient (β₁) is positive and statistically significant (p < 0.05), indicating that as GERD increases, Real GDP tends to increase correspondingly.
The Adjusted R² is approximately 0.494, suggesting that Log(GERD) explains about 49.4% of the variance in Log(Real GDP).
Thus, GERD can be considered a major explanatory factor contributing to economic growth.

Model 2: Adding a Confounding Variable (Log_Real_GDP ~ Log_GERD + GDP_per_Capita)
Model 2 adds GDP per Capita as a confounding variable to the basic model. The variables Total Population and Labor Force Size were unavailable in the dataset and therefore excluded.
The analysis shows that GDP per Capita is statistically insignificant (p = 0.491), indicating that it does not have a meaningful impact on Real GDP in this model.
Meanwhile, the coefficient for Log(GERD) remains statistically significant (p = 0.003), suggesting that the positive relationship between GERD and Real GDP persists even after controlling for GDP per Capita.
The Adjusted R² slightly decreases to 0.476, possibly due to the added confounder not substantially improving explanatory power, or as a result of penalization for increased model complexity.

Model 3: Adding Mediating Variables (Log_Real_GDP ~ Log_GERD + GDP_per_Capita + Innovation Variables)
Model 3 includes mediating variables — Resident / Non-resident Patent Applications, R&D Researchers per Million People,
High-tech Export Share (% of Manufactured Exports), and Business R&D Personnel (FTE) — in addition to Log(GERD) and GDP per Capita.
The coefficient for Log(GERD) slightly decreases (β ≈ 0.380) but remains statistically significant (p = 0.020).
This suggests that part of the relationship between GERD and Real GDP may be mediated by innovation, human capital, or technological diffusion.
Among the mediators, Resident Patent Applications shows a near-significant result (p = 0.053), implying that domestic patent activity might partially explain how GERD affects Real GDP.
Other mediators were not statistically significant. The Adjusted R² increases substantially to approximately 0.700, indicating that including mediating variables substantially improves the model’s explanatory power.

Model 4: Adding a Moderating Effect (Log_Real_GDP ~ Log_GERD * GovFinanced_BERD_pct + Mediators + Confounder)
Model 4 adds an interaction term between Log(GERD) and Government-financed BERD (%) to test for a moderating effect.
The interaction term (Log_GERD × GovFinanced_BERD_pct) is highly significant (p = 0.001), suggesting that the effect of GERD on Real GDP varies depending on the proportion of government-financed R&D expenditure.
The coefficient for the interaction term (β = -0.0895) is negative, implying that as the share of government financing in R&D increases, the positive impact of GERD on Real GDP tends to weaken.
The coefficient for Log(GERD) itself increases (β ≈ 1.070) compared to Model 3 and remains highly significant (p < 0.001).
This represents the effect of GERD on Real GDP when the moderator (Government-financed BERD) equals zero.
Given the significant interaction, the effect size of GERD should be interpreted conditionally on the level of government financing.
The Adjusted R² further increases to approximately 0.775, showing that Model 4 provides the best overall explanatory power.

Key Findings and Implications
1. Relationship between GERD and Real GDP
Across all models, Log(GERD) consistently shows a statistically significant and positive relationship with Real GDP. This provides empirical support for the notion that R&D investment is a key driver of economic growth.
2. Mediating Effects
Resident Patent Applications partially mediates the relationship between GERD and Real GDP, suggesting that R&D expenditure contributes to economic growth indirectly through innovation activities. Other mediators were not statistically significant, indicating that the mediating strength may be limited.
3. Moderating Effects
Government-financed BERD (%) moderates the relationship between GERD and Real GDP. The positive effect of GERD on GDP tends to weaken as the proportion of government-financed R&D increases. This finding implies that the efficiency of R&D investment may vary depending on the balance between public and private funding structures.
4. Model Fit Comparison
The Adjusted R² values steadily improve as the models expand (0.494 → 0.476 → 0.700 → 0.775). This indicates that incorporating mediating and moderating variables yields a more comprehensive and accurate explanation of Real GDP fluctuations compared to a simple model.

Conclusion
The multiple regression analysis demonstrates that GERD exerts a consistently positive impact on Real GDP.
However, this effect operates through both indirect innovation pathways (e.g., patent applications) and conditional moderation effects depending on the level of government-financed R&D.
The results reveal that the relationship is not a simple “R&D → Growth” linear link, but rather a multi-stage causal chain — “R&D → Innovation → Productivity → Growth” — that is further conditioned by policy environments such as government funding ratios.
Therefore, future R&D policies should focus not merely on expanding total expenditure, but also on optimizing the qualitative composition of investment — balancing government and private funding, strengthening human capital, and promoting innovation output efficiency.
"""
with st.expander("본문 펼치기 / 접기", expanded=False):
    st.markdown(long_text)

# 다운로드(선택)
st.download_button(
    "⬇️ Download narrative as .txt",
    data=long_text,
    file_name="ACDT_G31_Report_Summary.txt",
    mime="text/plain",
)
st.caption("© ACDT Group 31 — Streamlit Report View")